Add support for passing arguments to containers
microsoft/aspire pull request #1121
Opened 2023-11-29 22:02 UTC by BrennanConroy

Closes https://github.com/dotnet/aspire/issues/177

Questions:
* Should we have a separate annotation type for container args instead of reusing executable args?
* Args need to be separated into different list items. Should we make it `params string[]`? I'm worried about arbitrarily splitting the args by space in case something like `'Program Files'` needs to be in a single list entry.
* Manifest generation is very hardcoded right now so it doesn't automatically support args in containers. Should it be more flexible i.e. it knows how to write specific annotations as well as specific resources? So we don't need to add args to `WriteContainer`

2023-11-29 22:17 UTC, smitpatel commented
Filed https://github.com/dotnet/aspire/issues/1122 for follow-up for dashboard to light up the information.

2023-11-30 16:34 UTC, karolz-ms requested changes
Thanks Brennan. I think we need a couple of changes, but overall looks good.

2023-11-30 22:14 UTC, karolz-ms approved these changes

2023-11-30 23:27 UTC, merged

2023-12-05 15:44 UTC, davidfowl commented
@BrennanConroy we should also consider making this a callback so that we can get allocated endpoints from other resources.