Add column title for details column on the 'Traces' page
microsoft/aspire pull request #1574
Opened 2024-01-06 20:47 UTC by stbau04

Add column title for details column on the 'Traces' page

Fixes: https://github.com/dotnet/aspire/issues/1535

Traces:
![grafik](https://github.com/dotnet/aspire/assets/67107950/cc562733-8970-4ab5-9a83-b025467d82de)

Structured logs:
![grafik](https://github.com/dotnet/aspire/assets/67107950/e383ec5d-21d9-4a16-9532-db9b8440e754)

2024-01-07 12:51 UTC, stbau04 commented
FYI: it took me four runs to pass all checks
Once a unit test failed due to a kubeconfig that could not be deleted/modified, once the linux tests timed out and once the windows tests timed out. I don't think that the problems are related to my changes, are there any known issues with the pipeline?

2024-01-10 16:54 UTC, adamint requested changes

2024-01-10 16:54 UTC, adamint commented on src/Aspire.Dashboard/Components/Pages/Traces.razor
> +                <TemplateColumn Title="@ControlsStringsLoc[nameof(ControlsStrings.DetailsColumnHeader)]">
Could you put this string in `TraceDetail.resx`?

2024-01-10 16:54 UTC, adamint commented on src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor
> +                            <TemplateColumn Title="@ControlsStringsLoc[nameof(ControlsStrings.DetailsColumnHeader)]">
Could you put this string in `StructuredLogs` instead of `ControlsStrings`?

2024-01-10 16:55 UTC, adamint commented
> are there any known issues with the pipeline 

Not AFAIK @stbau04, let me know if you continue to run into this pipeline issue.

2024-01-10 20:02 UTC, adamint approved these changes

2024-01-11 06:14 UTC, JamesNK approved these changes

2024-01-11 06:15 UTC, merged

2024-01-11 06:15 UTC, JamesNK commented
Thanks!