Make user secrets lazy load.
microsoft/aspire pull request #2998
Opened 2024-03-19 03:06 UTC by mitchdenny

Changes loading of user secrets to be lazy.

2024-03-19 03:16 UTC, davidfowl commented on src/Aspire.Hosting.Azure/Provisioning/Provisioners/AzureProvisioner.cs
>                  var provisioningContext = await provisioningContextLazy.Value.ConfigureAwait(false);
Remove this.

2024-03-19 09:54 UTC, mitchdenny commented
/azp run

2024-03-19 14:05 UTC, davidfowl approved these changes

2024-03-19 20:42 UTC, davidfowl commented
/azp run

2024-03-20 00:30 UTC, davidfowl requested changes
Hmm, I just realized this isn't right. I might have been wrong here 😭. We can't save this as it'll overwrite the file.

2024-03-20 00:52 UTC, mitchdenny commented
> Hmm, I just realized this isn't right. I might have been wrong here 😭. We can't save this as it'll overwrite the file.

I don't follow. It seems to work as expected.

2024-03-20 01:00 UTC, davidfowl approved these changes

2024-03-20 01:01 UTC, merged