Fix environment variable masking being reset on component re-render
microsoft/aspire pull request #3708
Opened 2024-04-15 18:01 UTC by adamint

Fixes #3693

We were setting the value of environment variable masks `OnParametersSet` to the view's default mask value, which is called after its parent pane's size changes and then re-rendered. This is only needed 1) on initial component render, to set masking to the default value, and 2) when the user toggles that default, which is already handled `ToggleMaskState`.

pre:
![environmentvariablesmaskpre](https://github.com/dotnet/aspire/assets/20359921/ff7c648e-89b7-4adb-ae1a-1894d456eac1)

post:
![environmentvariablesmaskpost](https://github.com/dotnet/aspire/assets/20359921/a6746538-1f59-4de1-a0d8-e08c34ce5f2f)

2024-04-15 18:50 UTC, kvenkatrajan approved these changes

2024-04-16 00:21 UTC, JamesNK requested changes
This doesn't work when switching between resources because code in OnAfterRender with firstRender check runs once.

Setting the value in `OnParametersSet` is the right place, but it should only happen if the `Resource` parameter changes. Add a private field that is set when it changes, then only update IsValueMasked when the private field and publich property are different.

2024-04-16 01:13 UTC, adamint commented
I’m extremely confused why a different component is not rendered for each resource. Thanks, I’ll make that change

2024-04-16 01:36 UTC, JamesNK commented
It is re-rendered when the resource changes, but you've placed the code inside firstRender block.

2024-04-17 00:38 UTC, JamesNK requested changes

2024-04-17 00:41 UTC, JamesNK commented
I don't understand why you're setting this in initialize AND set parameters AND after render. Does just doing this in OnParametersSet like I suggested not work?

2024-04-17 16:04 UTC, adamint commented
You're right, sorry.

2024-04-18 00:43 UTC, JamesNK approved these changes

2024-04-26 20:03 UTC, merged