Persist selected application in the Traces page
microsoft/aspire pull request #4564
Opened 2024-06-18 09:08 UTC by andrei-ungureanu-uipath

Fixes https://github.com/dotnet/aspire/issues/3041

Used the `IPageWithSessionAndUrlState` interface to persist the selected application. This brings to parity the _Traces_ page as all other pages (_Console_, _Structured_ & _Metrics_) use it to persist state. 
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/4564)

2024-06-18 17:52 UTC, adamint requested changes
Thank you very much for the contribution. This is very good, just a few changes that I'd love to happen before this is merged.

2024-06-18 17:52 UTC, adamint commented on src/Aspire.Dashboard/Components/Pages/Traces.razor.cs
> +        PageViewModel.SelectedApplication = _applicationViewModels.GetApplication(ApplicationName, _allApplication);
`viewModel` should be changed here, instead of `PageViewModel`

2024-06-18 17:52 UTC, adamint commented on src/Aspire.Dashboard/Components/Pages/Traces.razor.cs
> +        _ = Task.Run(async () =>
This statehaschanged invocation is not necessary 😄

2024-06-19 04:12 UTC, adamint commented
/azp run

2024-06-19 04:14 UTC, adamint commented
@andrei-ungureanu-uipath we are having some CI infrastructure issues, you will need to merge main into your branch as well as resolving the merge conflict before CI can pass.

I will approve afterwards

2024-06-19 12:54 UTC, adamint approved these changes

2024-07-01 08:54 UTC, andrei-ungureanu-uipath commented
@adamint are there any actions left on my part?

2024-07-16 15:16 UTC, adamint commented
/azp run

2024-07-16 18:15 UTC, merged